stages:
   - base
   - docker
   - build
   - publish

base-docker:
   stage: base
   tags:
      - linux
      - dedicated
   only:
      changes:
        - docker/linux/base/Dockerfile
   variables:
      IMAGE: $CI_REGISTRY/emptyewer/deepn-plus/base:latest
   script:
      - docker image inspect $IMAGE >/dev/null 2>&1 && docker rmi $IMAGE || echo "$IMAGE not present, skipping"
      - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
      - docker build . --rm --no-cache -t $IMAGE -f $CI_PROJECT_DIR/docker/linux/base/Dockerfile
      - docker push $IMAGE

linux-docker:
   stage: docker
   tags:
      - linux
      - dedicated
   variables:
      IMAGE: $CI_REGISTRY/emptyewer/deepn-plus/linux64:latest
   only:
      changes:
        - docker/linux/base/Dockerfile
        - docker/linux/Dockerfile
        - docker/linux/default
        - docker/linux/entrypoint.sh
   dependencies:
     - base-docker
   script:
      - docker image inspect $IMAGE >/dev/null 2>&1 && docker rmi $IMAGE || echo "$IMAGE not present, skipping"
      - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
      - docker build . --rm --no-cache -t $IMAGE -f $CI_PROJECT_DIR/docker/linux/Dockerfile
      - docker push $IMAGE

windows-docker:
   stage: docker
   tags:
      - linux
      - dedicated
   variables:
      IMAGE: $CI_REGISTRY/emptyewer/deepn-plus/windows64:latest
   only:
      changes:
        - docker/windows/Dockerfile
        - docker/windows/default
        - docker/windows/entrypoint.sh
   script:
      - docker image inspect $IMAGE >/dev/null 2>&1 && docker rmi $IMAGE || echo "$IMAGE not present, skipping"
      - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
      - docker build . --rm --no-cache -t $IMAGE -f $CI_PROJECT_DIR/docker/windows/Dockerfile
      - docker push $IMAGE

mac-build:
   stage: build
   tags:
      - dedicated
      - mac
      - catalina
   variables:
      BUILD_DIR: $CI_PROJECT_DIR/build_mac_release
   before_script:
     - source $CI_PROJECT_DIR/env_vars
     - export MAC_COMPILED_OUTPUT=${PROJECT_FILE%%.*}_mac_64bit.7z
   script:
      - /usr/local/Cellar/qt@5/5.15.2/bin/qmake -o $BUILD_DIR/Makefile $CI_PROJECT_DIR/$PROJECT_FILE -spec macx-clang CONFIG+=x86_64 CONFIG-=qtquickcompiler
      - make -j4 -C $BUILD_DIR qmake_all
      - make -j4 -C $BUILD_DIR/deepn
      - make -j4 -C $BUILD_DIR/gene_count
      - make -j4 -C $BUILD_DIR/junction_make
      - cp -R -f $BUILD_DIR/deepn/DEEPN.app $BUILD_DIR/DEEPN.app
      - mkdir -p $BUILD_DIR/DEEPN.app/Contents/Apps/
      - cp -R -f $BUILD_DIR/gene_count/GeneCount.app $BUILD_DIR/DEEPN.app/Contents/Apps/GeneCount.app
      - cp -R -f $BUILD_DIR/junction_make/JunctionMake.app $BUILD_DIR/DEEPN.app/Contents/Apps/JunctionMake.app
      - 7z a -m0=ppmd -mx=9 $CI_PROJECT_DIR/$MAC_COMPILED_OUTPUT $BUILD_DIR/DEEPN.app
   artifacts:
      paths:
         - $CI_PROJECT_DIR/
      expire_in: '1 hour'

linux-build:
   stage: build
   tags:
      - linux
      - dedicated
   script:
      - source $CI_PROJECT_DIR/env_vars
      - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
      - docker run --rm --user $(id -u):$(id -g) -v $CI_PROJECT_DIR:$ROOT_DIR -e ROOT_DIR=$ROOT_DIR -e PROJECT_FILE=$PROJECT_FILE $CI_REGISTRY/emptyewer/deepn-plus/linux64:latest
   dependencies:
      - linux-docker
   artifacts:
      paths:
         - $CI_PROJECT_DIR/
      expire_in: '1 hour'

windows-build:
   stage: build
   tags:
      - linux
      - dedicated
   script:
      - source $CI_PROJECT_DIR/env_vars
      - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
      - docker run --rm --user $(id -u):$(id -g) -v $CI_PROJECT_DIR:$ROOT_DIR -e ROOT_DIR=$ROOT_DIR -e PROJECT_FILE=$PROJECT_FILE $CI_REGISTRY/emptyewer/deepn-plus/windows64:latest
   dependencies:
      - windows-docker
   artifacts:
      paths:
         - $CI_PROJECT_DIR/
      expire_in: '1 hour'

publish:
   image: venkykrishna/gitlab-release
   stage: publish
   dependencies:
      - linux-build
      - windows-build
      - mac-build
   script:
     - source $CI_PROJECT_DIR/env_vars
     - export WINDOWS_COMPILED_OUTPUT=${PROJECT_FILE%%.*}_windows_64bit.7z
     - export LINUX_COMPILED_OUTPUT=${PROJECT_FILE%%.*}_linux_64bit.7z
     - export MAC_COMPILED_OUTPUT=${PROJECT_FILE%%.*}_mac_64bit.7z
     - gitlab-release --message "Latest Release ($(date))" $CI_PROJECT_DIR/$LINUX_COMPILED_OUTPUT $CI_PROJECT_DIR/$WINDOWS_COMPILED_OUTPUT $CI_PROJECT_DIR/$MAC_COMPILED_OUTPUT
